## Conda environment for https://github.com/dkirkby/metastudy

name: meta
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.7
  - pip           # ensures that any pip installs only modify this env
  - ipython
  - jupyter
  - jupyterlab    # needed for "jupyter lab"
  - ipykernel     # ensures that (base) nb_conda creates a kernel for this env
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - hdf5
  - pytables
  - pillow
  - libiconv       # needed by jupyter_contrib_nbextensions on some platforms
  - jupyter_contrib_nbextensions
  - emcee
  - galsim
  - ngmix
